package View;
import Control.EquipamentoController;
import Control.TipoEquipamentoController;
import DAO.TipoEquipamentoDAO;
import Model.Equipamento;
import Model.Pessoa;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class ViewConsultarEquipamento extends javax.swing.JFrame {
    /**
     * Creates new form ViewPrincipal
     */
    public ViewConsultarEquipamento(){
        initComponents();
    }
    List<Equipamento> listaEquipamento;
    EquipamentoController equipamentoControl=new EquipamentoController();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_titulo = new javax.swing.JLabel();
        txt_subtitulo = new javax.swing.JLabel();
        txt_identificacao = new javax.swing.JLabel();
        edt_recebeIdentificacao = new javax.swing.JTextField();
        btn_consultarEquipamento = new javax.swing.JButton();
        edt_recebeIP = new javax.swing.JTextField();
        txt_ip = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_equipamento = new javax.swing.JTable();
        btn_editarEquipamento = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        btn_voltar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(440, 180));

        txt_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_titulo.setForeground(new java.awt.Color(255, 255, 255));
        txt_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background_blue.jpg"))); // NOI18N
        txt_titulo.setText("PREFEITURA DO SUCESSO");
        txt_titulo.setToolTipText("");
        txt_titulo.setFocusable(false);
        txt_titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txt_subtitulo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_subtitulo.setText("Consultar Equipamento");
        txt_subtitulo.setToolTipText("");
        txt_subtitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txt_subtitulo.setFocusable(false);
        txt_subtitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txt_identificacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_identificacao.setText("Identificação");

        edt_recebeIdentificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_recebeIdentificacaoActionPerformed(evt);
            }
        });

        btn_consultarEquipamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_consultarEquipamento.setText("Consultar");
        btn_consultarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarEquipamentoActionPerformed(evt);
            }
        });

        txt_ip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_ip.setText("IP");

        tbl_equipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificação", "IP", "Tipo", "Setor", "Secretaria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_equipamento);
        if (tbl_equipamento.getColumnModel().getColumnCount() > 0) {
            tbl_equipamento.getColumnModel().getColumn(0).setResizable(false);
            tbl_equipamento.getColumnModel().getColumn(1).setResizable(false);
            tbl_equipamento.getColumnModel().getColumn(2).setResizable(false);
            tbl_equipamento.getColumnModel().getColumn(3).setResizable(false);
            tbl_equipamento.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_editarEquipamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_editarEquipamento.setText("Editar");
        btn_editarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarEquipamentoActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_voltar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_voltar1.setText("Remover");
        btn_voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(txt_identificacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edt_recebeIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(txt_ip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edt_recebeIP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_consultarEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(btn_editarEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_voltar1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_subtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_ip)
                        .addComponent(edt_recebeIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edt_recebeIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_identificacao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_consultarEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_voltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_editarEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        btn_voltar();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_consultarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarEquipamentoActionPerformed
        consultar();
        btn_consultarEquipamento.setVisible(false);
    }//GEN-LAST:event_btn_consultarEquipamentoActionPerformed

    private void edt_recebeIdentificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_recebeIdentificacaoActionPerformed
    }//GEN-LAST:event_edt_recebeIdentificacaoActionPerformed

    private void btn_editarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarEquipamentoActionPerformed
        if(tbl_equipamento.getSelectedRow()>=0){
            ViewEditarEquipamento view=new ViewEditarEquipamento();
            view.setEquipamento(listaEquipamento.get(tbl_equipamento.getSelectedRow()));
            view.setVisible(true);
            this.setVisible(false);
        }else
            JOptionPane.showMessageDialog(null,"Selecione um equipamento para editar");
    }//GEN-LAST:event_btn_editarEquipamentoActionPerformed

    private void btn_voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar1ActionPerformed
        if(tbl_equipamento.getSelectedRow()>=0){
            btn_remover();
        }else
            JOptionPane.showMessageDialog(null,"Selecione um equipamento para remover");
    }//GEN-LAST:event_btn_voltar1ActionPerformed
    public void consultar(){
        String identificacao=edt_recebeIdentificacao.getText();
        String ip=edt_recebeIP.getText();
        
        listaEquipamento=equipamentoControl.findByNameIp(identificacao,ip);
        for (int i=0; i<listaEquipamento.size(); i++){
            Equipamento equipamento=listaEquipamento.get(i);
            ((DefaultTableModel)tbl_equipamento.getModel()).addRow(new Object[]{
                (equipamento.getIdentificacaoEquipamento()),
                equipamento.getIpEquipamento(),
                equipamento.getTipoEquipamento().getTipoEquipamento(),
                equipamento.getSetor().getNomeSetor(),
                equipamento.getSetor().getSecretaria().getNomeSecretaria()
            
            });
        }
    }
    public void btn_voltar(){
        new ViewPrincipal().setVisible(true);
        this.setVisible(false);
    }
    public void limpar(){
        edt_recebeIP.setText(null);
        edt_recebeIdentificacao.setText(null);
    }
    
    public void btn_remover(){
        Equipamento equip=listaEquipamento.get(tbl_equipamento.getSelectedRow());
        System.out.println(equip.getIdentificacaoEquipamento());
        String nome=JOptionPane.showInputDialog("Para efetuar a exclusão escreva exatamente a identificão do equipamento: ");
        if(nome.equals(equip.getIdentificacaoEquipamento())){
            removerEquipamento(equip);
            ViewConsultarEquipamento v=new ViewConsultarEquipamento();
            v.edt_recebeIP.setText(this.edt_recebeIP.getText());
            v.edt_recebeIdentificacao.setText(this.edt_recebeIdentificacao.getText());
            v.btn_consultarEquipamento.setVisible(false);
            v.consultar();
            this.setVisible(false);
            v.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Identificação incorreta, tente novamente ou cancele");
        }
        

    }
    
    public void removerEquipamento(Equipamento equip){
        equipamentoControl.remove(equip);
        JOptionPane.showMessageDialog(null,"Equipamento removido");    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConsultarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConsultarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConsultarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConsultarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewConsultarEquipamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultarEquipamento;
    private javax.swing.JButton btn_editarEquipamento;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JButton btn_voltar1;
    private javax.swing.JTextField edt_recebeIP;
    private javax.swing.JTextField edt_recebeIdentificacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_equipamento;
    private javax.swing.JLabel txt_identificacao;
    private javax.swing.JLabel txt_ip;
    private javax.swing.JLabel txt_subtitulo;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
