package View;
import Control.EquipamentoController;
import Model.Equipamento;
import Model.Setor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class ViewEditarEquipamento extends javax.swing.JFrame{
    public ViewEditarEquipamento(){
        initComponents();
//        atualizarTabelaSetor();
    }
    Setor setor;
    Equipamento equipamento;
    EquipamentoController equipamentoControl=new EquipamentoController();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_titulo = new javax.swing.JLabel();
        txt_subtitulo = new javax.swing.JLabel();
        edt_recebeIdentificacao = new javax.swing.JTextField();
        edt_recebeIp = new javax.swing.JTextField();
        txt_identificacao = new javax.swing.JLabel();
        txt_ip = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_salvarEquipamento = new javax.swing.JButton();
        scr_tipoEquipamento = new javax.swing.JScrollPane();
        tbl_tipoEquipamento = new javax.swing.JTable();
        txt_setor = new javax.swing.JLabel();
        txt_secretaria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(440, 230));

        txt_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_titulo.setForeground(new java.awt.Color(255, 255, 255));
        txt_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background_blue.jpg"))); // NOI18N
        txt_titulo.setText("PREFEITURA DO SUCESSO");
        txt_titulo.setToolTipText("");
        txt_titulo.setFocusable(false);
        txt_titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txt_subtitulo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_subtitulo.setText("Editar Equipamento");
        txt_subtitulo.setToolTipText("");
        txt_subtitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txt_subtitulo.setFocusable(false);
        txt_subtitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txt_identificacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_identificacao.setText("Identificação");

        txt_ip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ip.setText("IP");

        btn_voltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_voltar.setText("Cancelar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_salvarEquipamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_salvarEquipamento.setText("Salvar");
        btn_salvarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarEquipamentoActionPerformed(evt);
            }
        });

        tbl_tipoEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de Equipamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scr_tipoEquipamento.setViewportView(tbl_tipoEquipamento);
        if (tbl_tipoEquipamento.getColumnModel().getColumnCount() > 0) {
            tbl_tipoEquipamento.getColumnModel().getColumn(0).setResizable(false);
        }

        txt_setor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_setor.setText("Setor: ");

        txt_secretaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_secretaria.setText("Secretaria:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 411, Short.MAX_VALUE)
            .addComponent(txt_subtitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_setor, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_secretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_identificacao)
                            .addComponent(txt_ip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edt_recebeIp)
                            .addComponent(edt_recebeIdentificacao)
                            .addComponent(scr_tipoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_salvarEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_voltar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_subtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(txt_secretaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_setor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_recebeIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_identificacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_recebeIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scr_tipoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_salvarEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        btn_voltar();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_salvarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarEquipamentoActionPerformed
        salvarEquipamento();
    }//GEN-LAST:event_btn_salvarEquipamentoActionPerformed
//    public void atualizarTabelaSecretaria(){
//        List<Secretaria> listaSecretaria=new SecretariaDAO().findAll();
//        for (int i=0; i<listaSecretaria.size(); i++) {
//            ((DefaultTableModel)tbl_secretaria.getModel()).addRow(new Object[]{
//                listaSecretaria.get(i).getCodigoSecretaria(),listaSecretaria.get(i).getSiglaSecretaria(),listaSecretaria.get(i).getNomeSecretaria()});
//        }
//    }
    
//    public void atualizarTabelaSetor(){
//        List<Setor> listaSetor=new SetorDAO().findAll();
//        for (int i=0; i<listaSetor.size(); i++) {
//            ((DefaultTableModel)tbl_setor.getModel()).addRow(new Object[]{
//                (listaSetor.get(i).getSecretaria().getSiglaSecretaria()).toUpperCase(),listaSetor.get(i).getSecretaria().getNomeSecretaria(),listaSetor.get(i).getNomeSetor(),listaSetor.get(i).getTelefone(),listaSetor.get(i).getIpRede()});
//        }
//        
//    }
    
    public void setEquipamento(Equipamento equipamento){
        this.equipamento=equipamento;
        txt_secretaria.setText(txt_secretaria.getText()+" "+equipamento.getSetor().getSecretaria().getNomeSecretaria());
        txt_setor.setText(txt_setor.getText()+" "+equipamento.getSetor().getNomeSetor());
        edt_recebeIdentificacao.setText(equipamento.getIdentificacaoEquipamento());
        edt_recebeIp.setText(equipamento.getIpEquipamento());
        ((DefaultTableModel)tbl_tipoEquipamento.getModel()).addRow(new Object[]{
                equipamento.getTipoEquipamento().getTipoEquipamento()});
    }
        
    
    public void salvarEquipamento(){
        String ip=edt_recebeIp.getText();
        String identificacao=edt_recebeIdentificacao.getText();
        
        equipamento.setIdentificacaoEquipamento(identificacao);
        equipamento.setIpEquipamento(ip);
        
        equipamentoControl.update(equipamento);

        JOptionPane.showMessageDialog(null, "Edição salva");
    }
    public void btn_voltar(){
        new ViewPrincipal().setVisible(true);
        this.setVisible(false);
    }
    
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditarEquipamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salvarEquipamento;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JTextField edt_recebeIdentificacao;
    private javax.swing.JTextField edt_recebeIp;
    private javax.swing.JScrollPane scr_tipoEquipamento;
    private javax.swing.JTable tbl_tipoEquipamento;
    private javax.swing.JLabel txt_identificacao;
    private javax.swing.JLabel txt_ip;
    private javax.swing.JLabel txt_secretaria;
    private javax.swing.JLabel txt_setor;
    private javax.swing.JLabel txt_subtitulo;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
